name: CI-CD Pipeline

on:
  push:
    branches: [ "main", "dev" ] 
  pull_request:
    branches: [ "main" ]

jobs:
  # --- ETAPA 1: INTEGRACIÓN CONTINUA (CI) ---
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Ejecutar Linter
      run: npm run lint

     Tarjeta: Configurar Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar Pruebas
      run: npm test

    # --- FEEDBACK EN CASO DE FALLA  ---
    - name: 🚨 Notificar Falla en Slack
      if: failure()
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "❌ ¡La etapa de Integración Continua ha fallado!"
        message_format: |
          *Descripción:* Falló el análisis estático o la suite de QA.
          *Rama:* `${{ github.ref_name }}`
          *Disparado por:* @${{ github.actor }}
          *Commit:* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # --- ETAPA 2: ENTREGA CONTINUA (CD) ---
  deploy:
    needs: build-and-test 
    runs-on: ubuntu-latest
    # FILTRO DE SEGURIDAD EXTREMO: Solo despliega si el cambio ocurre en la rama main
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout del codigo
      uses: actions/checkout@v4

    - name: Desplegar en GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: . 
        branch: gh-pages

    # --- FEEDBACK EN CASO DE ÉXITO ---
    - name: 🎉 Notificar Éxito en Slack
      if: success()
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: ${{ job.status }}
        notification_title: "🚀 ¡Despliegue Exitoso en Producción!"
        message_format: |
          *Descripción:* El artefacto pasó QA y se desplegó correctamente.
          *Rama:* `${{ github.ref_name }}`
          *Disparado por:* @${{ github.actor }}
          *URL de Producción:* https://elisa-ab.github.io/ProyectoIC/
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}